services:
  - type: web
    name: listmonk
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    image:
      url: docker.io/jeamzx/listmonk:jeam-v1
    healthCheckPath: /admin
    envVars:
      - key: DATABASE_URL
        sync: false
